DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS follows;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  descrip TEXT,
  password TEXT NOT NULL,
  admin INTEGER DEFAULT 0,
  registered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  avatar INTEGER DEFAULT 0,
  restricted INTEGER DEFAULT 0
);

CREATE TABLE post (
  pid INTEGER PRIMARY KEY AUTOINCREMENT,
  uid INTEGER NOT NULL,
  content TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (uid) REFERENCES user (id)
);

CREATE TABLE follows (
  fid INTEGER NOT NULL,
  uid INTEGER NOT NULL,
  PRIMARY KEY (fid, uid),
  FOREIGN KEY (fid) REFERENCES user (id),
  FOREIGN KEY (uid) REFERENCES user (id)
);
